version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "laravelapp"
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "laravel_sanctum"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "tj6w7#BGDY."
    volumes:
      - ./db:/var/lib/mysql
